### ISSUE TITLE
Plot: VDP 25/PLOT Command

### ISSUE THREAD

**Issue by wmikrut** [tomm/fab-agon-emulator#63]
I do not have an AGON Lite (yet) and I have started practicing on the emulator.
I noticed that when I draw a line, the coordinates appear to be backwards.

PLOT 69,0,950
PLOT 13,1300,950
Will draw a line at the top of the screen. 

I expected the 0,0 coordinate to be top left of the screen but it is actually located at bottom left.
Is this the expected action for the emulator and VDP in the Agon?

**Comment by stevesims** [comment]
Yes, this is expected behaviour

Location 0,0 on an Agon is the bottom left of the screen, and the Y coordinates go up the screen, like they do when you're plotting a graph on paper.  this is consistent with the BBC Micro, on which the Agon's video system is modelled.  the coordinate system supports X values in the range 0-1279, and Y from 0-1023, which the VDP then scales to the actual pixel coordinates on the screen (the Agon doesn't have any screen modes any where near 1280x1024 resolution :D )

the Agon's VDP does support an alternate coordinate system - you can change to using "pixel coordinate" by turning off the logical screen scaling using `VDU 23,0,&C0,0` - see https://agonconsole8.github.io/agon-docs/vdp/System-Commands/#vdu-23-0-c0-n-turn-logical-screen-scaling-on-and-off
when you do that 0,0 is the top left, and coordinates will then match pixel locations
